"""Add profile fields to user table

Revision ID: 301e930ec861
Revises: 
Create Date: 2025-12-21 21:14:31.037384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '301e930ec861'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add profile fields to the existing users table
    op.add_column('users', sa.Column('software_experience', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hardware_knowledge', sa.String(), nullable=True))
    op.add_column('users', sa.Column('interests', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'interests')
    op.drop_column('users', 'hardware_knowledge')
    op.drop_column('users', 'software_experience')
    # ### end Alembic commands ###
